services:
  - type: web
    name: taskly
    runtime: docker
    plan: starter
    autoDeployTrigger: commit
    dockerfilePath: Dockerfile
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_NAME
        value: Taskly
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: taskly-db
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info

databases:
  - name: taskly-db
    plan: basic-256mb